---
name: Check Autobuilder for Errors
author: Chris Bush
description: 'Checks Snooty Autobuilder jobs for errors.'
branding:
  icon: 'check-square'
  color: 'white'
runs:
  using: 'node16'
  steps:
    - shell: bash
      run: cd "${{github.action_path}}" && npm run build && node . "${{github.actor}}/${{github.event.pull_request.head.repo.full_name}}/${{github.head_ref}}"
